### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by dmytro-khrusch**

### CODE REVIEW

**Comment by guvra** [comment]
Hi @dmytro-khrusch,

Thanks for the contribution :+1: 

The smile quality suite standard is not fully implemented in your PR.

cf. module-debug-toolbar for an example implementation:

- require-dev in composer.json : https://github.com/Smile-SA/magento2-module-debug-toolbar/blob/master/composer.json#L28
- phpcs.xml.dist : https://github.com/Smile-SA/magento2-module-debug-toolbar/blob/master/phpcs.xml.dist
- phpmd.xml.dist : https://github.com/Smile-SA/magento2-module-debug-toolbar/blob/master/phpmd.xml.dist
- phpstan.neon.dist : https://github.com/Smile-SA/magento2-module-debug-toolbar/blob/master/phpstan.neon.dist
- github workflow : https://github.com/Smile-SA/magento2-module-debug-toolbar/blob/master/.github/workflows/static-analysis.yaml (you will need to add an additional step to upload the ssk key required by akeneo)

Also a good practice is to include [.gitattributes](https://github.com/Smile-SA/magento2-module-debug-toolbar/blob/master/.gitattributes) and [.gitignore](https://github.com/Smile-SA/magento2-module-debug-toolbar/blob/master/.gitignore) files.

`@package` annotation isn't useful, the namespace already provides this information.

[Optional] For easier maintenance of the module, i would advise to remove the header phpdoc from all files (the one with the DISCLAIMER). I recently removed them from the debug toolbar module (cf. https://github.com/Smile-SA/magento2-module-debug-toolbar/commit/4a30efcc3090dfb579de8fd6d2f129e0fe64c638).

Do you want more time to implement the quality suite?
I can wait for next week to review the code.

**Comment by dmytro-khrusch** [comment]
Hi @guvra 
I have made changes (except the "github workflow" point) as per your recommendation.

**Comment by guvra** [comment]
I can see that the quality suite was added, but the code was not updated, so a lot of errors are reported by phpcs / phpmd.

Most phpcs errors can be automatically fixed by running `vendor/bin/phpcbf`.
If you use phpcbf, there will be a few things to manually clean up. For example, there will still be a few useless `@param` annotations that must be manually removed (for example in CustomerEntityRecord::setAttributesValue and CustomerEntityRecord::__construct).

Your github workflow script seems broken because of the ssh key, I can help you try solving this issue if you want, but won't be available until monday.

**Comment by guvra** [comment]
Also a few things are missing from composer.json file:

- magento 2 repository, cf. https://github.com/Smile-SA/magento2-module-debug-toolbar/blob/master/composer.json#L38
- config section:

```json
    "config": {
        "allow-plugins": {
            "magento/composer-dependency-version-audit-plugin": true,
            "magento/magento-composer-installer": true,
            "dealerdirect/phpcodesniffer-composer-installer": true
        },
        "sort-packages": true
    }
```

**Comment by dmytro-khrusch** [comment]
@guvra 
code updated

**Comment by guvra** [comment]
@dmytro-khrusch Could you push your code to the master branch of this repository?

I cleaned up some code (e.g. adding constructor property promotion), but I can't push the changes because I don't have any write access to your fork.

**Comment by guvra** [comment]
Also in Helper/Import/Option.php, you overrided the function `matchEntity` that is already defined in the parent class.
I fear that it will be very tedious to maintain this class because of that.

Wouldn't have it been possible to use the method `customMatchEntityJob` instead?
It was designed specifically to add custom logic, cf. the phpdoc of this method:

```php
    /**
     * This function is used to be able to add custom job in matchEntity without overriding it
     *
     * @param string $pimKey
     * @param string $entityTable
     * @param string $import
     * @param string|null $prefix
     *
     * @return void
     */
    protected function customMatchEntityJob(string $pimKey, string $entityTable, string $import, string $prefix = null): void
    {
        // Intentionally do nothing. Must be overridden
    }
```

**Comment by guvra** [comment]
I moved the code to a branch named `initial-release` on this repo so I can have write access to the code.
I pushed some changes (e.g. adding constructor property promotion).

I'm closing this PR and reopening a new one.

**Pull request closed without merging**
